INFO 2025-03-12 02:43:54,896 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 02:43:55,552 sol_prices_collector Собираем цены с  2025-03-11 22:40:00+00:00 до 2025-03-12 02:43:55.552335+00:00...
INFO 2025-03-12 02:43:56,079 sol_prices_collector Цены собраны!
INFO 2025-03-12 02:43:56,094 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 02:44:56,084 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 02:44:56,322 sol_prices_collector Собираем цены с  2025-03-12 02:43:00+00:00 до 2025-03-12 02:44:56.321973+00:00...
INFO 2025-03-12 02:44:57,037 sol_prices_collector Цены собраны!
INFO 2025-03-12 02:44:57,044 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 02:45:57,041 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 02:45:57,266 sol_prices_collector Собираем цены с  2025-03-12 02:44:00+00:00 до 2025-03-12 02:45:57.266056+00:00...
INFO 2025-03-12 02:45:57,734 sol_prices_collector Цены собраны!
INFO 2025-03-12 02:45:57,739 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 03:46:40,599 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 03:46:40,859 sol_prices_collector Собираем цены с  2025-03-12 02:45:00+00:00 до 2025-03-12 03:46:40.859221+00:00...
INFO 2025-03-12 03:46:41,386 sol_prices_collector Цены собраны!
INFO 2025-03-12 03:46:41,396 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 03:47:41,391 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 03:47:41,615 sol_prices_collector Собираем цены с  2025-03-12 03:46:00+00:00 до 2025-03-12 03:47:41.615300+00:00...
INFO 2025-03-12 03:47:42,086 sol_prices_collector Цены собраны!
INFO 2025-03-12 03:47:42,092 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 03:48:42,090 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 03:48:42,319 sol_prices_collector Собираем цены с  2025-03-12 03:47:00+00:00 до 2025-03-12 03:48:42.319078+00:00...
INFO 2025-03-12 03:48:42,790 sol_prices_collector Цены собраны!
INFO 2025-03-12 03:48:42,796 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 03:49:42,795 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 03:49:43,026 sol_prices_collector Собираем цены с  2025-03-12 03:48:00+00:00 до 2025-03-12 03:49:43.026168+00:00...
INFO 2025-03-12 03:49:43,493 sol_prices_collector Цены собраны!
INFO 2025-03-12 03:49:43,499 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 03:50:43,498 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 03:50:43,727 sol_prices_collector Собираем цены с  2025-03-12 03:49:00+00:00 до 2025-03-12 03:50:43.727808+00:00...
INFO 2025-03-12 03:50:44,567 sol_prices_collector Цены собраны!
INFO 2025-03-12 03:50:44,572 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 03:51:44,570 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 03:51:44,798 sol_prices_collector Собираем цены с  2025-03-12 03:50:00+00:00 до 2025-03-12 03:51:44.798353+00:00...
INFO 2025-03-12 03:51:45,356 sol_prices_collector Цены собраны!
INFO 2025-03-12 03:51:45,361 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 03:52:45,361 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 03:52:45,586 sol_prices_collector Собираем цены с  2025-03-12 03:51:00+00:00 до 2025-03-12 03:52:45.586248+00:00...
INFO 2025-03-12 03:52:46,093 sol_prices_collector Цены собраны!
INFO 2025-03-12 03:52:46,099 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 03:53:46,097 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 03:53:46,327 sol_prices_collector Собираем цены с  2025-03-12 03:52:00+00:00 до 2025-03-12 03:53:46.327712+00:00...
INFO 2025-03-12 03:53:46,801 sol_prices_collector Цены собраны!
INFO 2025-03-12 03:53:46,806 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 03:54:46,805 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 03:54:47,033 sol_prices_collector Собираем цены с  2025-03-12 03:53:00+00:00 до 2025-03-12 03:54:47.033744+00:00...
INFO 2025-03-12 03:54:47,545 sol_prices_collector Цены собраны!
INFO 2025-03-12 03:54:47,551 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 03:55:47,550 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 03:55:47,776 sol_prices_collector Собираем цены с  2025-03-12 03:54:00+00:00 до 2025-03-12 03:55:47.776061+00:00...
INFO 2025-03-12 03:55:48,296 sol_prices_collector Цены собраны!
INFO 2025-03-12 03:55:48,302 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 03:56:48,301 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 03:56:48,531 sol_prices_collector Собираем цены с  2025-03-12 03:55:00+00:00 до 2025-03-12 03:56:48.531887+00:00...
INFO 2025-03-12 03:56:49,038 sol_prices_collector Цены собраны!
INFO 2025-03-12 03:56:49,043 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 03:57:49,042 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 03:57:49,272 sol_prices_collector Собираем цены с  2025-03-12 03:56:00+00:00 до 2025-03-12 03:57:49.272850+00:00...
INFO 2025-03-12 03:57:49,784 sol_prices_collector Цены собраны!
INFO 2025-03-12 03:57:49,790 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 03:58:49,789 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 03:58:50,012 sol_prices_collector Собираем цены с  2025-03-12 03:57:00+00:00 до 2025-03-12 03:58:50.011972+00:00...
INFO 2025-03-12 03:58:50,517 sol_prices_collector Цены собраны!
INFO 2025-03-12 03:58:50,523 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 03:59:50,522 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 03:59:50,745 sol_prices_collector Собираем цены с  2025-03-12 03:58:00+00:00 до 2025-03-12 03:59:50.745783+00:00...
INFO 2025-03-12 03:59:51,216 sol_prices_collector Цены собраны!
INFO 2025-03-12 03:59:51,221 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:00:51,221 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:00:51,465 sol_prices_collector Собираем цены с  2025-03-12 03:59:00+00:00 до 2025-03-12 04:00:51.464967+00:00...
INFO 2025-03-12 04:00:51,977 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:00:51,983 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:01:51,982 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:01:52,204 sol_prices_collector Собираем цены с  2025-03-12 04:00:00+00:00 до 2025-03-12 04:01:52.204308+00:00...
INFO 2025-03-12 04:01:52,680 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:01:52,685 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:02:52,684 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:02:52,908 sol_prices_collector Собираем цены с  2025-03-12 04:01:00+00:00 до 2025-03-12 04:02:52.908069+00:00...
INFO 2025-03-12 04:02:53,442 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:02:53,447 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:03:53,446 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:03:53,669 sol_prices_collector Собираем цены с  2025-03-12 04:02:00+00:00 до 2025-03-12 04:03:53.668977+00:00...
INFO 2025-03-12 04:03:54,173 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:03:54,178 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:04:54,177 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:04:54,401 sol_prices_collector Собираем цены с  2025-03-12 04:03:00+00:00 до 2025-03-12 04:04:54.401524+00:00...
INFO 2025-03-12 04:04:54,866 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:04:54,871 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:05:54,869 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:05:55,097 sol_prices_collector Собираем цены с  2025-03-12 04:04:00+00:00 до 2025-03-12 04:05:55.097390+00:00...
INFO 2025-03-12 04:05:55,903 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:05:55,909 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:06:55,909 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:06:56,132 sol_prices_collector Собираем цены с  2025-03-12 04:05:00+00:00 до 2025-03-12 04:06:56.132517+00:00...
INFO 2025-03-12 04:06:56,600 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:06:56,606 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:07:56,604 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:07:56,833 sol_prices_collector Собираем цены с  2025-03-12 04:06:00+00:00 до 2025-03-12 04:07:56.833920+00:00...
INFO 2025-03-12 04:07:57,299 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:07:57,304 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:08:57,303 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:08:57,531 sol_prices_collector Собираем цены с  2025-03-12 04:07:00+00:00 до 2025-03-12 04:08:57.531675+00:00...
INFO 2025-03-12 04:08:57,999 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:08:58,004 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:09:58,003 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:09:58,227 sol_prices_collector Собираем цены с  2025-03-12 04:08:00+00:00 до 2025-03-12 04:09:58.227910+00:00...
INFO 2025-03-12 04:09:58,687 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:09:58,692 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:10:58,691 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:10:58,914 sol_prices_collector Собираем цены с  2025-03-12 04:09:00+00:00 до 2025-03-12 04:10:58.914829+00:00...
INFO 2025-03-12 04:10:59,380 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:10:59,384 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:11:59,383 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:11:59,604 sol_prices_collector Собираем цены с  2025-03-12 04:10:00+00:00 до 2025-03-12 04:11:59.604853+00:00...
INFO 2025-03-12 04:12:00,069 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:12:00,074 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:13:00,073 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:13:00,295 sol_prices_collector Собираем цены с  2025-03-12 04:11:00+00:00 до 2025-03-12 04:13:00.295862+00:00...
INFO 2025-03-12 04:13:00,762 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:13:00,767 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:14:00,766 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:14:00,988 sol_prices_collector Собираем цены с  2025-03-12 04:12:00+00:00 до 2025-03-12 04:14:00.988851+00:00...
INFO 2025-03-12 04:14:01,453 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:14:01,458 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:15:01,456 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:15:01,679 sol_prices_collector Собираем цены с  2025-03-12 04:14:00+00:00 до 2025-03-12 04:15:01.679758+00:00...
INFO 2025-03-12 04:15:02,140 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:15:02,145 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:16:02,144 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:16:02,368 sol_prices_collector Собираем цены с  2025-03-12 04:15:00+00:00 до 2025-03-12 04:16:02.368745+00:00...
INFO 2025-03-12 04:16:02,834 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:16:02,839 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:17:02,838 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:17:03,062 sol_prices_collector Собираем цены с  2025-03-12 04:16:00+00:00 до 2025-03-12 04:17:03.062300+00:00...
INFO 2025-03-12 04:17:03,525 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:17:03,530 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:18:03,528 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:18:03,758 sol_prices_collector Собираем цены с  2025-03-12 04:17:00+00:00 до 2025-03-12 04:18:03.758970+00:00...
INFO 2025-03-12 04:18:04,713 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:18:04,719 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:19:04,718 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:19:04,945 sol_prices_collector Собираем цены с  2025-03-12 04:18:00+00:00 до 2025-03-12 04:19:04.945930+00:00...
INFO 2025-03-12 04:19:05,410 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:19:05,415 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:20:05,414 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:20:05,638 sol_prices_collector Собираем цены с  2025-03-12 04:19:00+00:00 до 2025-03-12 04:20:05.638654+00:00...
INFO 2025-03-12 04:20:06,614 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:20:06,619 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:21:06,619 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:21:06,843 sol_prices_collector Собираем цены с  2025-03-12 04:20:00+00:00 до 2025-03-12 04:21:06.843170+00:00...
INFO 2025-03-12 04:21:07,744 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:21:07,749 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:22:07,748 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:22:07,979 sol_prices_collector Собираем цены с  2025-03-12 04:21:00+00:00 до 2025-03-12 04:22:07.979211+00:00...
INFO 2025-03-12 04:22:08,886 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:22:08,891 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:23:08,891 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:23:09,112 sol_prices_collector Собираем цены с  2025-03-12 04:22:00+00:00 до 2025-03-12 04:23:09.112456+00:00...
INFO 2025-03-12 04:23:09,903 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:23:09,908 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:24:09,907 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:24:10,129 sol_prices_collector Собираем цены с  2025-03-12 04:23:00+00:00 до 2025-03-12 04:24:10.129858+00:00...
INFO 2025-03-12 04:24:11,029 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:24:11,034 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:25:11,032 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:25:11,255 sol_prices_collector Собираем цены с  2025-03-12 04:24:00+00:00 до 2025-03-12 04:25:11.255711+00:00...
INFO 2025-03-12 04:25:12,155 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:25:12,160 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:26:12,158 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:26:12,380 sol_prices_collector Собираем цены с  2025-03-12 04:25:00+00:00 до 2025-03-12 04:26:12.380095+00:00...
INFO 2025-03-12 04:26:13,286 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:26:13,292 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:27:13,291 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:27:13,513 sol_prices_collector Собираем цены с  2025-03-12 04:26:00+00:00 до 2025-03-12 04:27:13.513307+00:00...
INFO 2025-03-12 04:27:14,422 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:27:14,427 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:28:14,425 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:28:14,647 sol_prices_collector Собираем цены с  2025-03-12 04:27:00+00:00 до 2025-03-12 04:28:14.647806+00:00...
INFO 2025-03-12 04:28:15,446 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:28:15,451 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:29:15,450 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:29:15,674 sol_prices_collector Собираем цены с  2025-03-12 04:28:00+00:00 до 2025-03-12 04:29:15.674030+00:00...
INFO 2025-03-12 04:29:16,577 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:29:16,582 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:30:16,581 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:30:16,808 sol_prices_collector Собираем цены с  2025-03-12 04:29:00+00:00 до 2025-03-12 04:30:16.808701+00:00...
INFO 2025-03-12 04:30:17,594 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:30:17,599 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:31:17,598 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:31:17,820 sol_prices_collector Собираем цены с  2025-03-12 04:30:00+00:00 до 2025-03-12 04:31:17.820530+00:00...
INFO 2025-03-12 04:31:18,725 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:31:18,730 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:32:18,729 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:32:18,952 sol_prices_collector Собираем цены с  2025-03-12 04:31:00+00:00 до 2025-03-12 04:32:18.952702+00:00...
INFO 2025-03-12 04:32:19,857 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:32:19,863 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:33:19,861 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:33:20,089 sol_prices_collector Собираем цены с  2025-03-12 04:32:00+00:00 до 2025-03-12 04:33:20.089456+00:00...
INFO 2025-03-12 04:33:20,883 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:33:20,888 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:34:20,887 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:34:21,113 sol_prices_collector Собираем цены с  2025-03-12 04:33:00+00:00 до 2025-03-12 04:34:21.113523+00:00...
INFO 2025-03-12 04:34:21,905 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:34:21,910 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:35:21,908 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:35:22,135 sol_prices_collector Собираем цены с  2025-03-12 04:34:00+00:00 до 2025-03-12 04:35:22.135133+00:00...
INFO 2025-03-12 04:35:23,041 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:35:23,046 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:36:23,045 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:36:23,267 sol_prices_collector Собираем цены с  2025-03-12 04:35:00+00:00 до 2025-03-12 04:36:23.267916+00:00...
INFO 2025-03-12 04:36:24,164 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:36:24,169 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:37:24,169 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:37:24,395 sol_prices_collector Собираем цены с  2025-03-12 04:36:00+00:00 до 2025-03-12 04:37:24.395057+00:00...
INFO 2025-03-12 04:37:25,296 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:37:25,301 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:38:25,299 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:38:25,523 sol_prices_collector Собираем цены с  2025-03-12 04:37:00+00:00 до 2025-03-12 04:38:25.523158+00:00...
INFO 2025-03-12 04:38:26,441 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:38:26,447 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:39:26,446 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:39:26,668 sol_prices_collector Собираем цены с  2025-03-12 04:38:00+00:00 до 2025-03-12 04:39:26.668865+00:00...
INFO 2025-03-12 04:39:27,460 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:39:27,465 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:40:27,463 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:40:27,711 sol_prices_collector Собираем цены с  2025-03-12 04:39:00+00:00 до 2025-03-12 04:40:27.711203+00:00...
INFO 2025-03-12 04:40:28,626 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:40:28,631 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:41:28,629 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:41:28,851 sol_prices_collector Собираем цены с  2025-03-12 04:40:00+00:00 до 2025-03-12 04:41:28.851880+00:00...
INFO 2025-03-12 04:41:29,754 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:41:29,759 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:42:29,758 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:42:29,985 sol_prices_collector Собираем цены с  2025-03-12 04:41:00+00:00 до 2025-03-12 04:42:29.985147+00:00...
INFO 2025-03-12 04:42:30,892 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:42:30,897 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:43:30,895 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:43:31,121 sol_prices_collector Собираем цены с  2025-03-12 04:42:00+00:00 до 2025-03-12 04:43:31.121800+00:00...
INFO 2025-03-12 04:43:32,048 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:43:32,053 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:44:32,052 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:44:32,282 sol_prices_collector Собираем цены с  2025-03-12 04:43:00+00:00 до 2025-03-12 04:44:32.282085+00:00...
INFO 2025-03-12 04:44:33,191 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:44:33,197 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:45:33,195 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:45:33,419 sol_prices_collector Собираем цены с  2025-03-12 04:44:00+00:00 до 2025-03-12 04:45:33.419000+00:00...
INFO 2025-03-12 04:45:34,324 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:45:34,329 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:46:34,328 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:46:34,554 sol_prices_collector Собираем цены с  2025-03-12 04:45:00+00:00 до 2025-03-12 04:46:34.554816+00:00...
INFO 2025-03-12 04:46:40,478 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:46:40,483 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:47:40,482 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:47:40,707 sol_prices_collector Собираем цены с  2025-03-12 04:46:00+00:00 до 2025-03-12 04:47:40.707288+00:00...
INFO 2025-03-12 04:47:41,492 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:47:41,497 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:48:41,496 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:48:41,718 sol_prices_collector Собираем цены с  2025-03-12 04:47:00+00:00 до 2025-03-12 04:48:41.718818+00:00...
INFO 2025-03-12 04:48:42,510 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:48:42,515 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:49:42,514 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:49:42,737 sol_prices_collector Собираем цены с  2025-03-12 04:48:00+00:00 до 2025-03-12 04:49:42.737285+00:00...
INFO 2025-03-12 04:49:43,636 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:49:43,641 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:50:43,641 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:50:43,875 sol_prices_collector Собираем цены с  2025-03-12 04:49:00+00:00 до 2025-03-12 04:50:43.875954+00:00...
INFO 2025-03-12 04:50:44,676 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:50:44,682 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:51:44,681 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:51:44,908 sol_prices_collector Собираем цены с  2025-03-12 04:50:00+00:00 до 2025-03-12 04:51:44.908276+00:00...
INFO 2025-03-12 04:51:46,055 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:51:46,060 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:52:46,059 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:52:46,283 sol_prices_collector Собираем цены с  2025-03-12 04:51:00+00:00 до 2025-03-12 04:52:46.283464+00:00...
INFO 2025-03-12 04:52:47,205 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:52:47,210 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:53:47,209 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:53:47,432 sol_prices_collector Собираем цены с  2025-03-12 04:52:00+00:00 до 2025-03-12 04:53:47.432236+00:00...
INFO 2025-03-12 04:53:48,340 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:53:48,345 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:54:48,344 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:54:48,572 sol_prices_collector Собираем цены с  2025-03-12 04:53:00+00:00 до 2025-03-12 04:54:48.572706+00:00...
INFO 2025-03-12 04:54:49,474 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:54:49,479 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:55:49,478 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:55:49,701 sol_prices_collector Собираем цены с  2025-03-12 04:54:00+00:00 до 2025-03-12 04:55:49.701961+00:00...
INFO 2025-03-12 04:55:50,498 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:55:50,504 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:56:50,502 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:56:50,723 sol_prices_collector Собираем цены с  2025-03-12 04:55:00+00:00 до 2025-03-12 04:56:50.723855+00:00...
INFO 2025-03-12 04:56:51,634 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:56:51,639 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:57:51,638 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:57:51,865 sol_prices_collector Собираем цены с  2025-03-12 04:56:00+00:00 до 2025-03-12 04:57:51.865262+00:00...
INFO 2025-03-12 04:57:52,667 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:57:52,672 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:58:52,671 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:58:52,897 sol_prices_collector Собираем цены с  2025-03-12 04:57:00+00:00 до 2025-03-12 04:58:52.897963+00:00...
INFO 2025-03-12 04:58:53,829 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:58:53,833 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 04:59:53,832 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 04:59:54,056 sol_prices_collector Собираем цены с  2025-03-12 04:58:00+00:00 до 2025-03-12 04:59:54.056811+00:00...
INFO 2025-03-12 04:59:54,957 sol_prices_collector Цены собраны!
INFO 2025-03-12 04:59:54,962 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:00:54,961 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:00:55,184 sol_prices_collector Собираем цены с  2025-03-12 04:59:00+00:00 до 2025-03-12 05:00:55.184404+00:00...
INFO 2025-03-12 05:00:55,967 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:00:55,973 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:01:55,971 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:01:56,195 sol_prices_collector Собираем цены с  2025-03-12 05:00:00+00:00 до 2025-03-12 05:01:56.195749+00:00...
INFO 2025-03-12 05:01:57,102 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:01:57,107 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:02:57,106 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:02:57,331 sol_prices_collector Собираем цены с  2025-03-12 05:01:00+00:00 до 2025-03-12 05:02:57.331317+00:00...
INFO 2025-03-12 05:02:58,252 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:02:58,257 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:03:58,256 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:03:58,483 sol_prices_collector Собираем цены с  2025-03-12 05:02:00+00:00 до 2025-03-12 05:03:58.483679+00:00...
INFO 2025-03-12 05:03:59,391 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:03:59,396 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:04:59,395 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:04:59,618 sol_prices_collector Собираем цены с  2025-03-12 05:03:00+00:00 до 2025-03-12 05:04:59.618758+00:00...
INFO 2025-03-12 05:05:00,520 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:05:00,525 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:06:00,523 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:06:00,745 sol_prices_collector Собираем цены с  2025-03-12 05:04:00+00:00 до 2025-03-12 05:06:00.745882+00:00...
INFO 2025-03-12 05:06:01,557 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:06:01,562 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:07:01,562 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:07:01,786 sol_prices_collector Собираем цены с  2025-03-12 05:06:00+00:00 до 2025-03-12 05:07:01.786086+00:00...
INFO 2025-03-12 05:07:02,694 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:07:02,699 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:08:02,698 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:08:02,930 sol_prices_collector Собираем цены с  2025-03-12 05:07:00+00:00 до 2025-03-12 05:08:02.930068+00:00...
INFO 2025-03-12 05:08:03,859 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:08:03,864 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:09:03,862 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:09:04,089 sol_prices_collector Собираем цены с  2025-03-12 05:08:00+00:00 до 2025-03-12 05:09:04.089221+00:00...
INFO 2025-03-12 05:09:05,016 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:09:05,021 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:10:05,021 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:10:05,241 sol_prices_collector Собираем цены с  2025-03-12 05:09:00+00:00 до 2025-03-12 05:10:05.241331+00:00...
INFO 2025-03-12 05:10:06,035 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:10:06,040 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:11:06,039 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:11:06,270 sol_prices_collector Собираем цены с  2025-03-12 05:10:00+00:00 до 2025-03-12 05:11:06.269993+00:00...
INFO 2025-03-12 05:11:07,179 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:11:07,184 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:12:07,183 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:12:07,412 sol_prices_collector Собираем цены с  2025-03-12 05:11:00+00:00 до 2025-03-12 05:12:07.412267+00:00...
INFO 2025-03-12 05:12:08,320 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:12:08,325 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:13:08,323 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:13:08,548 sol_prices_collector Собираем цены с  2025-03-12 05:12:00+00:00 до 2025-03-12 05:13:08.548041+00:00...
INFO 2025-03-12 05:13:09,453 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:13:09,458 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:14:09,457 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:14:09,682 sol_prices_collector Собираем цены с  2025-03-12 05:13:00+00:00 до 2025-03-12 05:14:09.682350+00:00...
INFO 2025-03-12 05:14:10,471 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:14:10,476 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:15:10,475 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:15:10,700 sol_prices_collector Собираем цены с  2025-03-12 05:14:00+00:00 до 2025-03-12 05:15:10.700009+00:00...
INFO 2025-03-12 05:15:11,619 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:15:11,625 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:16:11,623 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:16:11,847 sol_prices_collector Собираем цены с  2025-03-12 05:15:00+00:00 до 2025-03-12 05:16:11.847641+00:00...
INFO 2025-03-12 05:16:12,639 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:16:12,645 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:17:12,643 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:17:12,866 sol_prices_collector Собираем цены с  2025-03-12 05:16:00+00:00 до 2025-03-12 05:17:12.866812+00:00...
INFO 2025-03-12 05:17:13,777 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:17:13,782 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:18:13,780 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:18:14,009 sol_prices_collector Собираем цены с  2025-03-12 05:17:00+00:00 до 2025-03-12 05:18:14.009477+00:00...
INFO 2025-03-12 05:18:14,926 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:18:14,931 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:19:14,930 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:19:15,152 sol_prices_collector Собираем цены с  2025-03-12 05:18:00+00:00 до 2025-03-12 05:19:15.152764+00:00...
INFO 2025-03-12 05:19:15,939 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:19:15,944 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:20:15,943 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:20:16,173 sol_prices_collector Собираем цены с  2025-03-12 05:19:00+00:00 до 2025-03-12 05:20:16.173870+00:00...
INFO 2025-03-12 05:20:17,095 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:20:17,101 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:21:17,100 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:21:17,328 sol_prices_collector Собираем цены с  2025-03-12 05:20:00+00:00 до 2025-03-12 05:21:17.328159+00:00...
INFO 2025-03-12 05:21:18,231 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:21:18,237 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:22:18,235 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:22:18,457 sol_prices_collector Собираем цены с  2025-03-12 05:21:00+00:00 до 2025-03-12 05:22:18.457289+00:00...
INFO 2025-03-12 05:22:19,360 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:22:19,365 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:23:19,364 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:23:19,590 sol_prices_collector Собираем цены с  2025-03-12 05:22:00+00:00 до 2025-03-12 05:23:19.590206+00:00...
INFO 2025-03-12 05:23:20,385 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:23:20,390 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:24:20,389 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:24:20,615 sol_prices_collector Собираем цены с  2025-03-12 05:23:00+00:00 до 2025-03-12 05:24:20.615636+00:00...
INFO 2025-03-12 05:24:21,532 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:24:21,537 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:25:21,536 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:25:21,766 sol_prices_collector Собираем цены с  2025-03-12 05:24:00+00:00 до 2025-03-12 05:25:21.766016+00:00...
INFO 2025-03-12 05:25:22,672 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:25:22,677 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:26:22,675 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:26:22,897 sol_prices_collector Собираем цены с  2025-03-12 05:25:00+00:00 до 2025-03-12 05:26:22.897240+00:00...
INFO 2025-03-12 05:26:23,691 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:26:23,696 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-12 05:27:23,696 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-12 05:27:23,927 sol_prices_collector Собираем цены с  2025-03-12 05:26:00+00:00 до 2025-03-12 05:27:23.927557+00:00...
INFO 2025-03-12 05:27:24,842 sol_prices_collector Цены собраны!
INFO 2025-03-12 05:27:24,848 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-13 00:40:03,116 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
ERROR 2025-03-13 00:40:03,280 task_logger Ошибка при выполнении задачи collect_sol_prices_task: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432) | Traceback (most recent call last):
  File "/app/src/infra/celery/task_logger.py", line 12, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/celery/tasks.py", line 22, in collect_sol_prices_task
    asyncio.run(collect_prices_async())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/src/application/etl/sol_prices_collector.py", line 18, in collect_prices_async
    token = await Token.filter(address=config.solana.token_address).first()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/queryset.py", line 1134, in _execute
    instance_list = await self._db.executor_class(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base/executor.py", line 104, in execute_select
    _, raw_results = await self.db.execute_query(sql, values)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base_postgres/client.py", line 31, in _translate_exceptions
    return await self._translate_exceptions(func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/asyncpg/client.py", line 87, in _translate_exceptions
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/asyncpg/client.py", line 131, in execute_query
    async with self.acquire_connection() as connection:
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base/client.py", line 360, in __aenter__
    await self.ensure_connection()
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base/client.py", line 357, in ensure_connection
    await self.client.create_connection(with_db=True)
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/asyncpg/client.py", line 59, in create_connection
    self._pool = await self.create_pool(password=self.password, **self._template)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/asyncpg/client.py", line 70, in create_pool
    return await asyncpg.create_pool(None, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 418, in _async__init__
    await self._initialize()
  File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 445, in _initialize
    await first_ch.connect()
  File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 132, in connect
    self._con = await self._pool._get_new_connection()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 517, in _get_new_connection
    con = await self._connect(
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 2421, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 1075, in _connect
    raise last_error or exceptions.TargetServerAttributeNotMatched(
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 1049, in _connect
    conn = await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 886, in _connect_addr
    return await __connect_addr(params, True, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 931, in __connect_addr
    tr, pr = await connector
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 802, in _create_ssl_connection
    tr, pr = await loop.create_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1094, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432)

INFO 2025-03-15 20:38:59,481 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
ERROR 2025-03-15 20:38:59,589 task_logger Ошибка при выполнении задачи collect_sol_prices_task: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432) | Traceback (most recent call last):
  File "/app/src/infra/celery/task_logger.py", line 12, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/celery/tasks.py", line 24, in collect_sol_prices_task
    asyncio.run(collect_prices_async())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/src/application/etl/sol_prices_collector.py", line 18, in collect_prices_async
    token = await Token.filter(address=config.solana.token_address).first()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/queryset.py", line 1134, in _execute
    instance_list = await self._db.executor_class(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base/executor.py", line 104, in execute_select
    _, raw_results = await self.db.execute_query(sql, values)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base_postgres/client.py", line 31, in _translate_exceptions
    return await self._translate_exceptions(func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/asyncpg/client.py", line 87, in _translate_exceptions
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/asyncpg/client.py", line 131, in execute_query
    async with self.acquire_connection() as connection:
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base/client.py", line 360, in __aenter__
    await self.ensure_connection()
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base/client.py", line 357, in ensure_connection
    await self.client.create_connection(with_db=True)
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/asyncpg/client.py", line 59, in create_connection
    self._pool = await self.create_pool(password=self.password, **self._template)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/asyncpg/client.py", line 70, in create_pool
    return await asyncpg.create_pool(None, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 418, in _async__init__
    await self._initialize()
  File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 445, in _initialize
    await first_ch.connect()
  File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 132, in connect
    self._con = await self._pool._get_new_connection()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 517, in _get_new_connection
    con = await self._connect(
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 2421, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 1075, in _connect
    raise last_error or exceptions.TargetServerAttributeNotMatched(
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 1049, in _connect
    conn = await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 886, in _connect_addr
    return await __connect_addr(params, True, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 931, in __connect_addr
    tr, pr = await connector
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 802, in _create_ssl_connection
    tr, pr = await loop.create_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1094, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432)

INFO 2025-03-15 20:40:57,923 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
ERROR 2025-03-15 20:40:58,020 task_logger Ошибка при выполнении задачи collect_sol_prices_task: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432) | Traceback (most recent call last):
  File "/app/src/infra/celery/task_logger.py", line 12, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/celery/tasks.py", line 24, in collect_sol_prices_task
    asyncio.run(collect_prices_async())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/src/application/etl/sol_prices_collector.py", line 18, in collect_prices_async
    token = await Token.filter(address=config.solana.token_address).first()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/queryset.py", line 1134, in _execute
    instance_list = await self._db.executor_class(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base/executor.py", line 104, in execute_select
    _, raw_results = await self.db.execute_query(sql, values)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base_postgres/client.py", line 31, in _translate_exceptions
    return await self._translate_exceptions(func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/asyncpg/client.py", line 87, in _translate_exceptions
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/asyncpg/client.py", line 131, in execute_query
    async with self.acquire_connection() as connection:
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base/client.py", line 360, in __aenter__
    await self.ensure_connection()
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base/client.py", line 357, in ensure_connection
    await self.client.create_connection(with_db=True)
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/asyncpg/client.py", line 59, in create_connection
    self._pool = await self.create_pool(password=self.password, **self._template)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/asyncpg/client.py", line 70, in create_pool
    return await asyncpg.create_pool(None, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 418, in _async__init__
    await self._initialize()
  File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 445, in _initialize
    await first_ch.connect()
  File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 132, in connect
    self._con = await self._pool._get_new_connection()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 517, in _get_new_connection
    con = await self._connect(
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 2421, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 1075, in _connect
    raise last_error or exceptions.TargetServerAttributeNotMatched(
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 1049, in _connect
    conn = await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 886, in _connect_addr
    return await __connect_addr(params, True, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 931, in __connect_addr
    tr, pr = await connector
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 802, in _create_ssl_connection
    tr, pr = await loop.create_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1094, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432)

INFO 2025-03-15 20:41:35,179 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
ERROR 2025-03-15 20:41:35,280 task_logger Ошибка при выполнении задачи collect_sol_prices_task: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432) | Traceback (most recent call last):
  File "/app/src/infra/celery/task_logger.py", line 12, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/celery/tasks.py", line 24, in collect_sol_prices_task
    asyncio.run(collect_prices_async())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/src/application/etl/sol_prices_collector.py", line 18, in collect_prices_async
    token = await Token.filter(address=config.solana.token_address).first()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/queryset.py", line 1134, in _execute
    instance_list = await self._db.executor_class(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base/executor.py", line 104, in execute_select
    _, raw_results = await self.db.execute_query(sql, values)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base_postgres/client.py", line 31, in _translate_exceptions
    return await self._translate_exceptions(func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/asyncpg/client.py", line 87, in _translate_exceptions
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/asyncpg/client.py", line 131, in execute_query
    async with self.acquire_connection() as connection:
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base/client.py", line 360, in __aenter__
    await self.ensure_connection()
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base/client.py", line 357, in ensure_connection
    await self.client.create_connection(with_db=True)
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/asyncpg/client.py", line 59, in create_connection
    self._pool = await self.create_pool(password=self.password, **self._template)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tortoise/backends/asyncpg/client.py", line 70, in create_pool
    return await asyncpg.create_pool(None, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 418, in _async__init__
    await self._initialize()
  File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 445, in _initialize
    await first_ch.connect()
  File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 132, in connect
    self._con = await self._pool._get_new_connection()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 517, in _get_new_connection
    con = await self._connect(
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 2421, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 1075, in _connect
    raise last_error or exceptions.TargetServerAttributeNotMatched(
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 1049, in _connect
    conn = await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 886, in _connect_addr
    return await __connect_addr(params, True, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 931, in __connect_addr
    tr, pr = await connector
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 802, in _create_ssl_connection
    tr, pr = await loop.create_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1094, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432)

INFO 2025-03-15 20:42:56,593 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-15 20:42:56,945 sol_prices_collector Собираем цены с  2024-12-01 00:00:00+00:00 до 2024-12-01 16:40:00+00:00...
INFO 2025-03-15 20:42:57,467 sol_prices_collector Собираем цены с  2024-12-01 16:40:00+00:00 до 2024-12-02 09:20:00+00:00...
INFO 2025-03-15 20:42:57,931 sol_prices_collector Собираем цены с  2024-12-02 09:20:00+00:00 до 2024-12-03 02:00:00+00:00...
INFO 2025-03-15 20:42:58,385 sol_prices_collector Собираем цены с  2024-12-03 02:00:00+00:00 до 2024-12-03 18:40:00+00:00...
INFO 2025-03-15 20:42:58,838 sol_prices_collector Собираем цены с  2024-12-03 18:40:00+00:00 до 2024-12-04 11:20:00+00:00...
INFO 2025-03-15 20:42:59,288 sol_prices_collector Собираем цены с  2024-12-04 11:20:00+00:00 до 2024-12-05 04:00:00+00:00...
INFO 2025-03-15 20:42:59,742 sol_prices_collector Собираем цены с  2024-12-05 04:00:00+00:00 до 2024-12-05 20:40:00+00:00...
INFO 2025-03-15 20:43:00,202 sol_prices_collector Собираем цены с  2024-12-05 20:40:00+00:00 до 2024-12-06 13:20:00+00:00...
INFO 2025-03-15 20:43:01,609 sol_prices_collector Собираем цены с  2024-12-06 13:20:00+00:00 до 2024-12-07 06:00:00+00:00...
INFO 2025-03-15 20:43:02,061 sol_prices_collector Собираем цены с  2024-12-07 06:00:00+00:00 до 2024-12-07 22:40:00+00:00...
INFO 2025-03-15 20:43:02,514 sol_prices_collector Собираем цены с  2024-12-07 22:40:00+00:00 до 2024-12-08 15:20:00+00:00...
INFO 2025-03-15 20:43:02,964 sol_prices_collector Собираем цены с  2024-12-08 15:20:00+00:00 до 2024-12-09 08:00:00+00:00...
INFO 2025-03-15 20:43:03,419 sol_prices_collector Собираем цены с  2024-12-09 08:00:00+00:00 до 2024-12-10 00:40:00+00:00...
INFO 2025-03-15 20:43:03,943 sol_prices_collector Собираем цены с  2024-12-10 00:40:00+00:00 до 2024-12-10 17:20:00+00:00...
INFO 2025-03-15 20:43:04,415 sol_prices_collector Собираем цены с  2024-12-10 17:20:00+00:00 до 2024-12-11 10:00:00+00:00...
INFO 2025-03-15 20:43:04,867 sol_prices_collector Собираем цены с  2024-12-11 10:00:00+00:00 до 2024-12-12 02:40:00+00:00...
INFO 2025-03-15 20:43:05,318 sol_prices_collector Собираем цены с  2024-12-12 02:40:00+00:00 до 2024-12-12 19:20:00+00:00...
INFO 2025-03-15 20:43:05,766 sol_prices_collector Собираем цены с  2024-12-12 19:20:00+00:00 до 2024-12-13 12:00:00+00:00...
INFO 2025-03-15 20:43:06,218 sol_prices_collector Собираем цены с  2024-12-13 12:00:00+00:00 до 2024-12-14 04:40:00+00:00...
INFO 2025-03-15 20:43:06,677 sol_prices_collector Собираем цены с  2024-12-14 04:40:00+00:00 до 2024-12-14 21:20:00+00:00...
INFO 2025-03-15 20:43:07,124 sol_prices_collector Собираем цены с  2024-12-14 21:20:00+00:00 до 2024-12-15 14:00:00+00:00...
INFO 2025-03-15 20:43:07,613 sol_prices_collector Собираем цены с  2024-12-15 14:00:00+00:00 до 2024-12-16 06:40:00+00:00...
INFO 2025-03-15 20:43:08,069 sol_prices_collector Собираем цены с  2024-12-16 06:40:00+00:00 до 2024-12-16 23:20:00+00:00...
INFO 2025-03-15 20:43:08,522 sol_prices_collector Собираем цены с  2024-12-16 23:20:00+00:00 до 2024-12-17 16:00:00+00:00...
INFO 2025-03-15 20:43:08,984 sol_prices_collector Собираем цены с  2024-12-17 16:00:00+00:00 до 2024-12-18 08:40:00+00:00...
INFO 2025-03-15 20:43:09,436 sol_prices_collector Собираем цены с  2024-12-18 08:40:00+00:00 до 2024-12-19 01:20:00+00:00...
INFO 2025-03-15 20:43:09,883 sol_prices_collector Собираем цены с  2024-12-19 01:20:00+00:00 до 2024-12-19 18:00:00+00:00...
INFO 2025-03-15 20:43:10,332 sol_prices_collector Собираем цены с  2024-12-19 18:00:00+00:00 до 2024-12-20 10:40:00+00:00...
INFO 2025-03-15 20:43:10,790 sol_prices_collector Собираем цены с  2024-12-20 10:40:00+00:00 до 2024-12-21 03:20:00+00:00...
INFO 2025-03-15 20:43:11,246 sol_prices_collector Собираем цены с  2024-12-21 03:20:00+00:00 до 2024-12-21 20:00:00+00:00...
INFO 2025-03-15 20:43:11,707 sol_prices_collector Собираем цены с  2024-12-21 20:00:00+00:00 до 2024-12-22 12:40:00+00:00...
INFO 2025-03-15 20:43:12,155 sol_prices_collector Собираем цены с  2024-12-22 12:40:00+00:00 до 2024-12-23 05:20:00+00:00...
INFO 2025-03-15 20:43:12,611 sol_prices_collector Собираем цены с  2024-12-23 05:20:00+00:00 до 2024-12-23 22:00:00+00:00...
INFO 2025-03-15 20:43:13,064 sol_prices_collector Собираем цены с  2024-12-23 22:00:00+00:00 до 2024-12-24 14:40:00+00:00...
INFO 2025-03-15 20:43:13,516 sol_prices_collector Собираем цены с  2024-12-24 14:40:00+00:00 до 2024-12-25 07:20:00+00:00...
INFO 2025-03-15 20:43:13,966 sol_prices_collector Собираем цены с  2024-12-25 07:20:00+00:00 до 2024-12-26 00:00:00+00:00...
INFO 2025-03-15 20:43:14,417 sol_prices_collector Собираем цены с  2024-12-26 00:00:00+00:00 до 2024-12-26 16:40:00+00:00...
INFO 2025-03-15 20:43:14,869 sol_prices_collector Собираем цены с  2024-12-26 16:40:00+00:00 до 2024-12-27 09:20:00+00:00...
INFO 2025-03-15 20:43:15,319 sol_prices_collector Собираем цены с  2024-12-27 09:20:00+00:00 до 2024-12-28 02:00:00+00:00...
INFO 2025-03-15 20:43:15,771 sol_prices_collector Собираем цены с  2024-12-28 02:00:00+00:00 до 2024-12-28 18:40:00+00:00...
INFO 2025-03-15 20:43:16,226 sol_prices_collector Собираем цены с  2024-12-28 18:40:00+00:00 до 2024-12-29 11:20:00+00:00...
INFO 2025-03-15 20:43:16,680 sol_prices_collector Собираем цены с  2024-12-29 11:20:00+00:00 до 2024-12-30 04:00:00+00:00...
INFO 2025-03-15 20:43:17,133 sol_prices_collector Собираем цены с  2024-12-30 04:00:00+00:00 до 2024-12-30 20:40:00+00:00...
INFO 2025-03-15 20:43:17,580 sol_prices_collector Собираем цены с  2024-12-30 20:40:00+00:00 до 2024-12-31 13:20:00+00:00...
INFO 2025-03-15 20:43:18,035 sol_prices_collector Собираем цены с  2024-12-31 13:20:00+00:00 до 2025-01-01 06:00:00+00:00...
INFO 2025-03-15 20:43:18,493 sol_prices_collector Собираем цены с  2025-01-01 06:00:00+00:00 до 2025-01-01 22:40:00+00:00...
INFO 2025-03-15 20:43:18,948 sol_prices_collector Собираем цены с  2025-01-01 22:40:00+00:00 до 2025-01-02 15:20:00+00:00...
INFO 2025-03-15 20:43:19,404 sol_prices_collector Собираем цены с  2025-01-02 15:20:00+00:00 до 2025-01-03 08:00:00+00:00...
INFO 2025-03-15 20:43:19,855 sol_prices_collector Собираем цены с  2025-01-03 08:00:00+00:00 до 2025-01-04 00:40:00+00:00...
INFO 2025-03-15 20:43:20,306 sol_prices_collector Собираем цены с  2025-01-04 00:40:00+00:00 до 2025-01-04 17:20:00+00:00...
INFO 2025-03-15 20:43:20,758 sol_prices_collector Собираем цены с  2025-01-04 17:20:00+00:00 до 2025-01-05 10:00:00+00:00...
INFO 2025-03-15 20:43:21,213 sol_prices_collector Собираем цены с  2025-01-05 10:00:00+00:00 до 2025-01-06 02:40:00+00:00...
INFO 2025-03-15 20:43:21,668 sol_prices_collector Собираем цены с  2025-01-06 02:40:00+00:00 до 2025-01-06 19:20:00+00:00...
INFO 2025-03-15 20:43:22,123 sol_prices_collector Собираем цены с  2025-01-06 19:20:00+00:00 до 2025-01-07 12:00:00+00:00...
INFO 2025-03-15 20:43:22,574 sol_prices_collector Собираем цены с  2025-01-07 12:00:00+00:00 до 2025-01-08 04:40:00+00:00...
INFO 2025-03-15 20:43:23,034 sol_prices_collector Собираем цены с  2025-01-08 04:40:00+00:00 до 2025-01-08 21:20:00+00:00...
INFO 2025-03-15 20:43:23,522 sol_prices_collector Собираем цены с  2025-01-08 21:20:00+00:00 до 2025-01-09 14:00:00+00:00...
INFO 2025-03-15 20:43:23,974 sol_prices_collector Собираем цены с  2025-01-09 14:00:00+00:00 до 2025-01-10 06:40:00+00:00...
INFO 2025-03-15 20:43:24,427 sol_prices_collector Собираем цены с  2025-01-10 06:40:00+00:00 до 2025-01-10 23:20:00+00:00...
INFO 2025-03-15 20:43:24,884 sol_prices_collector Собираем цены с  2025-01-10 23:20:00+00:00 до 2025-01-11 16:00:00+00:00...
INFO 2025-03-15 20:43:25,333 sol_prices_collector Собираем цены с  2025-01-11 16:00:00+00:00 до 2025-01-12 08:40:00+00:00...
INFO 2025-03-15 20:43:25,791 sol_prices_collector Собираем цены с  2025-01-12 08:40:00+00:00 до 2025-01-13 01:20:00+00:00...
INFO 2025-03-15 20:43:26,246 sol_prices_collector Собираем цены с  2025-01-13 01:20:00+00:00 до 2025-01-13 18:00:00+00:00...
INFO 2025-03-15 20:43:26,705 sol_prices_collector Собираем цены с  2025-01-13 18:00:00+00:00 до 2025-01-14 10:40:00+00:00...
INFO 2025-03-15 20:43:27,161 sol_prices_collector Собираем цены с  2025-01-14 10:40:00+00:00 до 2025-01-15 03:20:00+00:00...
INFO 2025-03-15 20:43:27,609 sol_prices_collector Собираем цены с  2025-01-15 03:20:00+00:00 до 2025-01-15 20:00:00+00:00...
INFO 2025-03-15 20:43:28,066 sol_prices_collector Собираем цены с  2025-01-15 20:00:00+00:00 до 2025-01-16 12:40:00+00:00...
INFO 2025-03-15 20:43:28,520 sol_prices_collector Собираем цены с  2025-01-16 12:40:00+00:00 до 2025-01-17 05:20:00+00:00...
INFO 2025-03-15 20:43:28,976 sol_prices_collector Собираем цены с  2025-01-17 05:20:00+00:00 до 2025-01-17 22:00:00+00:00...
INFO 2025-03-15 20:43:29,428 sol_prices_collector Собираем цены с  2025-01-17 22:00:00+00:00 до 2025-01-18 14:40:00+00:00...
INFO 2025-03-15 20:43:29,882 sol_prices_collector Собираем цены с  2025-01-18 14:40:00+00:00 до 2025-01-19 07:20:00+00:00...
INFO 2025-03-15 20:43:30,335 sol_prices_collector Собираем цены с  2025-01-19 07:20:00+00:00 до 2025-01-20 00:00:00+00:00...
INFO 2025-03-15 20:43:30,799 sol_prices_collector Собираем цены с  2025-01-20 00:00:00+00:00 до 2025-01-20 16:40:00+00:00...
INFO 2025-03-15 20:43:31,254 sol_prices_collector Собираем цены с  2025-01-20 16:40:00+00:00 до 2025-01-21 09:20:00+00:00...
INFO 2025-03-15 20:43:31,707 sol_prices_collector Собираем цены с  2025-01-21 09:20:00+00:00 до 2025-01-22 02:00:00+00:00...
INFO 2025-03-15 20:43:32,166 sol_prices_collector Собираем цены с  2025-01-22 02:00:00+00:00 до 2025-01-22 18:40:00+00:00...
INFO 2025-03-15 20:43:32,628 sol_prices_collector Собираем цены с  2025-01-22 18:40:00+00:00 до 2025-01-23 11:20:00+00:00...
INFO 2025-03-15 20:43:33,093 sol_prices_collector Собираем цены с  2025-01-23 11:20:00+00:00 до 2025-01-24 04:00:00+00:00...
INFO 2025-03-15 20:43:33,545 sol_prices_collector Собираем цены с  2025-01-24 04:00:00+00:00 до 2025-01-24 20:40:00+00:00...
INFO 2025-03-15 20:43:33,998 sol_prices_collector Собираем цены с  2025-01-24 20:40:00+00:00 до 2025-01-25 13:20:00+00:00...
INFO 2025-03-15 20:43:34,461 sol_prices_collector Собираем цены с  2025-01-25 13:20:00+00:00 до 2025-01-26 06:00:00+00:00...
INFO 2025-03-15 20:43:34,909 sol_prices_collector Собираем цены с  2025-01-26 06:00:00+00:00 до 2025-01-26 22:40:00+00:00...
INFO 2025-03-15 20:43:35,371 sol_prices_collector Собираем цены с  2025-01-26 22:40:00+00:00 до 2025-01-27 15:20:00+00:00...
INFO 2025-03-15 20:43:35,830 sol_prices_collector Собираем цены с  2025-01-27 15:20:00+00:00 до 2025-01-28 08:00:00+00:00...
INFO 2025-03-15 20:43:36,284 sol_prices_collector Собираем цены с  2025-01-28 08:00:00+00:00 до 2025-01-29 00:40:00+00:00...
INFO 2025-03-15 20:43:36,901 sol_prices_collector Собираем цены с  2025-01-29 00:40:00+00:00 до 2025-01-29 17:20:00+00:00...
INFO 2025-03-15 20:43:37,353 sol_prices_collector Собираем цены с  2025-01-29 17:20:00+00:00 до 2025-01-30 10:00:00+00:00...
INFO 2025-03-15 20:43:37,805 sol_prices_collector Собираем цены с  2025-01-30 10:00:00+00:00 до 2025-01-31 02:40:00+00:00...
INFO 2025-03-15 20:43:38,260 sol_prices_collector Собираем цены с  2025-01-31 02:40:00+00:00 до 2025-01-31 19:20:00+00:00...
INFO 2025-03-15 20:43:38,710 sol_prices_collector Собираем цены с  2025-01-31 19:20:00+00:00 до 2025-02-01 12:00:00+00:00...
INFO 2025-03-15 20:43:39,167 sol_prices_collector Собираем цены с  2025-02-01 12:00:00+00:00 до 2025-02-02 04:40:00+00:00...
INFO 2025-03-15 20:43:39,622 sol_prices_collector Собираем цены с  2025-02-02 04:40:00+00:00 до 2025-02-02 21:20:00+00:00...
INFO 2025-03-15 20:43:40,299 sol_prices_collector Собираем цены с  2025-02-02 21:20:00+00:00 до 2025-02-03 14:00:00+00:00...
INFO 2025-03-15 20:43:40,751 sol_prices_collector Собираем цены с  2025-02-03 14:00:00+00:00 до 2025-02-04 06:40:00+00:00...
INFO 2025-03-15 20:43:41,203 sol_prices_collector Собираем цены с  2025-02-04 06:40:00+00:00 до 2025-02-04 23:20:00+00:00...
INFO 2025-03-15 20:43:41,660 sol_prices_collector Собираем цены с  2025-02-04 23:20:00+00:00 до 2025-02-05 16:00:00+00:00...
INFO 2025-03-15 20:43:42,114 sol_prices_collector Собираем цены с  2025-02-05 16:00:00+00:00 до 2025-02-06 08:40:00+00:00...
INFO 2025-03-15 20:43:42,571 sol_prices_collector Собираем цены с  2025-02-06 08:40:00+00:00 до 2025-02-07 01:20:00+00:00...
INFO 2025-03-15 20:43:43,023 sol_prices_collector Собираем цены с  2025-02-07 01:20:00+00:00 до 2025-02-07 18:00:00+00:00...
INFO 2025-03-15 20:43:43,478 sol_prices_collector Собираем цены с  2025-02-07 18:00:00+00:00 до 2025-02-08 10:40:00+00:00...
INFO 2025-03-15 20:43:43,937 sol_prices_collector Собираем цены с  2025-02-08 10:40:00+00:00 до 2025-02-09 03:20:00+00:00...
INFO 2025-03-15 20:43:44,389 sol_prices_collector Собираем цены с  2025-02-09 03:20:00+00:00 до 2025-02-09 20:00:00+00:00...
INFO 2025-03-15 20:43:44,842 sol_prices_collector Собираем цены с  2025-02-09 20:00:00+00:00 до 2025-02-10 12:40:00+00:00...
INFO 2025-03-15 20:43:45,293 sol_prices_collector Собираем цены с  2025-02-10 12:40:00+00:00 до 2025-02-11 05:20:00+00:00...
INFO 2025-03-15 20:43:45,745 sol_prices_collector Собираем цены с  2025-02-11 05:20:00+00:00 до 2025-02-11 22:00:00+00:00...
INFO 2025-03-15 20:43:46,199 sol_prices_collector Собираем цены с  2025-02-11 22:00:00+00:00 до 2025-02-12 14:40:00+00:00...
INFO 2025-03-15 20:43:46,651 sol_prices_collector Собираем цены с  2025-02-12 14:40:00+00:00 до 2025-02-13 07:20:00+00:00...
INFO 2025-03-15 20:43:47,104 sol_prices_collector Собираем цены с  2025-02-13 07:20:00+00:00 до 2025-02-14 00:00:00+00:00...
INFO 2025-03-15 20:43:47,554 sol_prices_collector Собираем цены с  2025-02-14 00:00:00+00:00 до 2025-02-14 16:40:00+00:00...
INFO 2025-03-15 20:43:48,008 sol_prices_collector Собираем цены с  2025-02-14 16:40:00+00:00 до 2025-02-15 09:20:00+00:00...
INFO 2025-03-15 20:43:48,466 sol_prices_collector Собираем цены с  2025-02-15 09:20:00+00:00 до 2025-02-16 02:00:00+00:00...
INFO 2025-03-15 20:43:48,918 sol_prices_collector Собираем цены с  2025-02-16 02:00:00+00:00 до 2025-02-16 18:40:00+00:00...
INFO 2025-03-15 20:43:49,368 sol_prices_collector Собираем цены с  2025-02-16 18:40:00+00:00 до 2025-02-17 11:20:00+00:00...
INFO 2025-03-15 20:43:49,825 sol_prices_collector Собираем цены с  2025-02-17 11:20:00+00:00 до 2025-02-18 04:00:00+00:00...
INFO 2025-03-15 20:43:50,280 sol_prices_collector Собираем цены с  2025-02-18 04:00:00+00:00 до 2025-02-18 20:40:00+00:00...
INFO 2025-03-15 20:43:50,736 sol_prices_collector Собираем цены с  2025-02-18 20:40:00+00:00 до 2025-02-19 13:20:00+00:00...
INFO 2025-03-15 20:43:51,186 sol_prices_collector Собираем цены с  2025-02-19 13:20:00+00:00 до 2025-02-20 06:00:00+00:00...
INFO 2025-03-15 20:43:51,647 sol_prices_collector Собираем цены с  2025-02-20 06:00:00+00:00 до 2025-02-20 22:40:00+00:00...
INFO 2025-03-15 20:43:52,097 sol_prices_collector Собираем цены с  2025-02-20 22:40:00+00:00 до 2025-02-21 15:20:00+00:00...
INFO 2025-03-15 20:43:52,547 sol_prices_collector Собираем цены с  2025-02-21 15:20:00+00:00 до 2025-02-22 08:00:00+00:00...
INFO 2025-03-15 20:43:53,000 sol_prices_collector Собираем цены с  2025-02-22 08:00:00+00:00 до 2025-02-23 00:40:00+00:00...
INFO 2025-03-15 20:43:53,449 sol_prices_collector Собираем цены с  2025-02-23 00:40:00+00:00 до 2025-02-23 17:20:00+00:00...
INFO 2025-03-15 20:43:53,902 sol_prices_collector Собираем цены с  2025-02-23 17:20:00+00:00 до 2025-02-24 10:00:00+00:00...
INFO 2025-03-15 20:43:54,581 sol_prices_collector Собираем цены с  2025-02-24 10:00:00+00:00 до 2025-02-25 02:40:00+00:00...
INFO 2025-03-15 20:43:55,035 sol_prices_collector Собираем цены с  2025-02-25 02:40:00+00:00 до 2025-02-25 19:20:00+00:00...
INFO 2025-03-15 20:43:55,491 sol_prices_collector Собираем цены с  2025-02-25 19:20:00+00:00 до 2025-02-26 12:00:00+00:00...
INFO 2025-03-15 20:43:55,952 sol_prices_collector Собираем цены с  2025-02-26 12:00:00+00:00 до 2025-02-27 04:40:00+00:00...
INFO 2025-03-15 20:43:56,405 sol_prices_collector Собираем цены с  2025-02-27 04:40:00+00:00 до 2025-02-27 21:20:00+00:00...
INFO 2025-03-15 20:43:56,857 sol_prices_collector Собираем цены с  2025-02-27 21:20:00+00:00 до 2025-02-28 14:00:00+00:00...
INFO 2025-03-15 20:43:57,307 sol_prices_collector Собираем цены с  2025-02-28 14:00:00+00:00 до 2025-03-01 06:40:00+00:00...
INFO 2025-03-15 20:43:57,762 sol_prices_collector Собираем цены с  2025-03-01 06:40:00+00:00 до 2025-03-01 23:20:00+00:00...
INFO 2025-03-15 20:43:58,209 sol_prices_collector Собираем цены с  2025-03-01 23:20:00+00:00 до 2025-03-02 16:00:00+00:00...
INFO 2025-03-15 20:43:58,741 sol_prices_collector Собираем цены с  2025-03-02 16:00:00+00:00 до 2025-03-03 08:40:00+00:00...
INFO 2025-03-15 20:43:59,191 sol_prices_collector Собираем цены с  2025-03-03 08:40:00+00:00 до 2025-03-04 01:20:00+00:00...
INFO 2025-03-15 20:43:59,644 sol_prices_collector Собираем цены с  2025-03-04 01:20:00+00:00 до 2025-03-04 18:00:00+00:00...
INFO 2025-03-15 20:44:01,045 sol_prices_collector Собираем цены с  2025-03-04 18:00:00+00:00 до 2025-03-05 10:40:00+00:00...
INFO 2025-03-15 20:44:01,497 sol_prices_collector Собираем цены с  2025-03-05 10:40:00+00:00 до 2025-03-06 03:20:00+00:00...
INFO 2025-03-15 20:44:01,954 sol_prices_collector Собираем цены с  2025-03-06 03:20:00+00:00 до 2025-03-06 20:00:00+00:00...
INFO 2025-03-15 20:44:02,402 sol_prices_collector Собираем цены с  2025-03-06 20:00:00+00:00 до 2025-03-07 12:40:00+00:00...
INFO 2025-03-15 20:44:02,869 sol_prices_collector Собираем цены с  2025-03-07 12:40:00+00:00 до 2025-03-08 05:20:00+00:00...
INFO 2025-03-15 20:44:03,320 sol_prices_collector Собираем цены с  2025-03-08 05:20:00+00:00 до 2025-03-08 22:00:00+00:00...
INFO 2025-03-15 20:44:03,769 sol_prices_collector Собираем цены с  2025-03-08 22:00:00+00:00 до 2025-03-09 14:40:00+00:00...
INFO 2025-03-15 20:44:04,221 sol_prices_collector Собираем цены с  2025-03-09 14:40:00+00:00 до 2025-03-10 07:20:00+00:00...
INFO 2025-03-15 20:44:04,672 sol_prices_collector Собираем цены с  2025-03-10 07:20:00+00:00 до 2025-03-11 00:00:00+00:00...
INFO 2025-03-15 20:44:05,131 sol_prices_collector Собираем цены с  2025-03-11 00:00:00+00:00 до 2025-03-11 16:40:00+00:00...
INFO 2025-03-15 20:44:05,585 sol_prices_collector Собираем цены с  2025-03-11 16:40:00+00:00 до 2025-03-12 09:20:00+00:00...
INFO 2025-03-15 20:44:06,044 sol_prices_collector Собираем цены с  2025-03-12 09:20:00+00:00 до 2025-03-13 02:00:00+00:00...
INFO 2025-03-15 20:44:06,497 sol_prices_collector Собираем цены с  2025-03-13 02:00:00+00:00 до 2025-03-13 18:40:00+00:00...
INFO 2025-03-15 20:44:06,953 sol_prices_collector Собираем цены с  2025-03-13 18:40:00+00:00 до 2025-03-14 11:20:00+00:00...
INFO 2025-03-15 20:44:07,458 sol_prices_collector Собираем цены с  2025-03-14 11:20:00+00:00 до 2025-03-15 04:00:00+00:00...
INFO 2025-03-15 20:44:07,917 sol_prices_collector Собираем цены с  2025-03-15 04:00:00+00:00 до 2025-03-15 20:40:00+00:00...
INFO 2025-03-15 20:44:08,369 sol_prices_collector Собираем цены с  2025-03-15 20:40:00+00:00 до 2025-03-15 20:42:56.945188+00:00...
INFO 2025-03-15 20:44:17,901 sol_prices_collector Цены собраны!
INFO 2025-03-15 20:44:17,936 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-24 15:17:50,681 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-24 15:17:50,681 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-24 15:17:50,795 sol_prices_collector Собираем цены с 2024-12-01 00:00:00+00:00 до 2025-03-24 15:17:50.795889+00:00...
INFO 2025-03-24 15:17:50,801 sol_prices_collector Собираем цены с 2024-12-01 00:00:00+00:00 до 2025-03-24 15:17:50.801899+00:00...
DEBUG 2025-03-24 15:17:51,219 sol_prices_collector Собираем за период 2024-12-01 00:00:00+00:00 - 2025-03-24 15:17:50.795889+00:00
DEBUG 2025-03-24 15:17:51,224 sol_prices_collector Собираем за период 2024-12-01 00:00:00+00:00 - 2025-03-24 15:17:50.801899+00:00
ERROR 2025-03-24 15:17:51,381 task_logger Ошибка при выполнении задачи collect_sol_prices_task: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.NotNullViolationError'>: null value in column "address" of relation "token" violates not-null constraint
DETAIL:  Failing row contains (0195c8bb-465c-7aca-b945-31e82a84a262, 2025-03-24 15:17:51.324676+00, 2025-03-24 15:17:51.324676+00, f, null, null, null, null, null, null).
[SQL: INSERT INTO token (id, created_at, updated_at, is_metadata_parsed) VALUES ($1::UUID, $2::TIMESTAMP WITH TIME ZONE, $3::TIMESTAMP WITH TIME ZONE, $4::BOOLEAN) ON CONFLICT DO NOTHING]
[parameters: [('0195c8bb-465c-7aca-b945-31e82a84a262', datetime.datetime(2025, 3, 24, 15, 17, 51, 324676), datetime.datetime(2025, 3, 24, 15, 17, 51, 324676), False), ('0195c8bb-465d-79c1-9535-b4d19e0c7354', datetime.datetime(2025, 3, 24, 15, 17, 51, 324736), datetime.datetime(2025, 3, 24, 15, 17, 51, 324736), False), ('0195c8bb-465e-796d-8570-9a68e43317ac', datetime.datetime(2025, 3, 24, 15, 17, 51, 324749), datetime.datetime(2025, 3, 24, 15, 17, 51, 324749), False), ('0195c8bb-465f-764b-82fb-a82585356348', datetime.datetime(2025, 3, 24, 15, 17, 51, 324759), datetime.datetime(2025, 3, 24, 15, 17, 51, 324759), False), ('0195c8bb-4660-7f70-a282-892ec8f426d8', datetime.datetime(2025, 3, 24, 15, 17, 51, 324769), datetime.datetime(2025, 3, 24, 15, 17, 51, 324769), False), ('0195c8bb-4661-737f-af61-09e0f176ea83', datetime.datetime(2025, 3, 24, 15, 17, 51, 324781), datetime.datetime(2025, 3, 24, 15, 17, 51, 324781), False), ('0195c8bb-4662-7ac2-802a-e6750f3bd4ca', datetime.datetime(2025, 3, 24, 15, 17, 51, 324788), datetime.datetime(2025, 3, 24, 15, 17, 51, 324788), False), ('0195c8bb-4663-7eba-a641-e3a7a574aca0', datetime.datetime(2025, 3, 24, 15, 17, 51, 324796), datetime.datetime(2025, 3, 24, 15, 17, 51, 324796), False)  ... displaying 10 of 1000 total bound parameter sets ...  ('0195c8bb-4a42-7067-b6d7-3adbde3ce43b', datetime.datetime(2025, 3, 24, 15, 17, 51, 330534), datetime.datetime(2025, 3, 24, 15, 17, 51, 330534), False), ('0195c8bb-4a43-70e6-94d8-5fdfb8345e65', datetime.datetime(2025, 3, 24, 15, 17, 51, 330541), datetime.datetime(2025, 3, 24, 15, 17, 51, 330541), False)]]
(Background on this error at: https://sqlalche.me/e/20/gkpj) | Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 561, in _executemany
    return await self._connection.executemany(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 390, in executemany
    return await self._executemany(command, args, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 1988, in _executemany
    result, _ = await self._do_execute(
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 2024, in _do_execute
    result = await executor(stmt, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 268, in bind_execute_many
asyncpg.exceptions.NotNullViolationError: null value in column "address" of relation "token" violates not-null constraint
DETAIL:  Failing row contains (0195c8bb-465c-7aca-b945-31e82a84a262, 2025-03-24 15:17:51.324676+00, 2025-03-24 15:17:51.324676+00, f, null, null, null, null, null, null).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1936, in _exec_single_context
    self.dialect.do_executemany(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 938, in do_executemany
    cursor.executemany(statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 573, in executemany
    return self._adapt_connection.await_(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 565, in _executemany
    self._handle_exception(error)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 497, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 780, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.IntegrityError: <class 'asyncpg.exceptions.NotNullViolationError'>: null value in column "address" of relation "token" violates not-null constraint
DETAIL:  Failing row contains (0195c8bb-465c-7aca-b945-31e82a84a262, 2025-03-24 15:17:51.324676+00, 2025-03-24 15:17:51.324676+00, f, null, null, null, null, null, null).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/src/infra/celery/task_logger.py", line 12, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/celery/tasks.py", line 24, in collect_sol_prices_task
    asyncio.run(collect_prices_async())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/src/application/etl/sol_prices_collector.py", line 47, in collect_prices_async
    await load_prices_to_db(prices_to_load)
  File "/app/src/application/etl/sol_prices_collector.py", line 113, in load_prices_to_db
    await SQLAlchemyTokenRepository(session).bulk_create(
  File "/app/src/infra/db/sqlalchemy/repositories/generic_repository.py", line 97, in bulk_create
    await connection.execute(stmt, values)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py", line 657, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1936, in _exec_single_context
    self.dialect.do_executemany(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 938, in do_executemany
    cursor.executemany(statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 573, in executemany
    return self._adapt_connection.await_(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 565, in _executemany
    self._handle_exception(error)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 497, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 780, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.IntegrityError: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.NotNullViolationError'>: null value in column "address" of relation "token" violates not-null constraint
DETAIL:  Failing row contains (0195c8bb-465c-7aca-b945-31e82a84a262, 2025-03-24 15:17:51.324676+00, 2025-03-24 15:17:51.324676+00, f, null, null, null, null, null, null).
[SQL: INSERT INTO token (id, created_at, updated_at, is_metadata_parsed) VALUES ($1::UUID, $2::TIMESTAMP WITH TIME ZONE, $3::TIMESTAMP WITH TIME ZONE, $4::BOOLEAN) ON CONFLICT DO NOTHING]
[parameters: [('0195c8bb-465c-7aca-b945-31e82a84a262', datetime.datetime(2025, 3, 24, 15, 17, 51, 324676), datetime.datetime(2025, 3, 24, 15, 17, 51, 324676), False), ('0195c8bb-465d-79c1-9535-b4d19e0c7354', datetime.datetime(2025, 3, 24, 15, 17, 51, 324736), datetime.datetime(2025, 3, 24, 15, 17, 51, 324736), False), ('0195c8bb-465e-796d-8570-9a68e43317ac', datetime.datetime(2025, 3, 24, 15, 17, 51, 324749), datetime.datetime(2025, 3, 24, 15, 17, 51, 324749), False), ('0195c8bb-465f-764b-82fb-a82585356348', datetime.datetime(2025, 3, 24, 15, 17, 51, 324759), datetime.datetime(2025, 3, 24, 15, 17, 51, 324759), False), ('0195c8bb-4660-7f70-a282-892ec8f426d8', datetime.datetime(2025, 3, 24, 15, 17, 51, 324769), datetime.datetime(2025, 3, 24, 15, 17, 51, 324769), False), ('0195c8bb-4661-737f-af61-09e0f176ea83', datetime.datetime(2025, 3, 24, 15, 17, 51, 324781), datetime.datetime(2025, 3, 24, 15, 17, 51, 324781), False), ('0195c8bb-4662-7ac2-802a-e6750f3bd4ca', datetime.datetime(2025, 3, 24, 15, 17, 51, 324788), datetime.datetime(2025, 3, 24, 15, 17, 51, 324788), False), ('0195c8bb-4663-7eba-a641-e3a7a574aca0', datetime.datetime(2025, 3, 24, 15, 17, 51, 324796), datetime.datetime(2025, 3, 24, 15, 17, 51, 324796), False)  ... displaying 10 of 1000 total bound parameter sets ...  ('0195c8bb-4a42-7067-b6d7-3adbde3ce43b', datetime.datetime(2025, 3, 24, 15, 17, 51, 330534), datetime.datetime(2025, 3, 24, 15, 17, 51, 330534), False), ('0195c8bb-4a43-70e6-94d8-5fdfb8345e65', datetime.datetime(2025, 3, 24, 15, 17, 51, 330541), datetime.datetime(2025, 3, 24, 15, 17, 51, 330541), False)]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

ERROR 2025-03-24 15:17:51,381 task_logger Ошибка при выполнении задачи collect_sol_prices_task: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.NotNullViolationError'>: null value in column "address" of relation "token" violates not-null constraint
DETAIL:  Failing row contains (0195c8bb-4658-70c7-bc59-3a3dc1c44dd7, 2025-03-24 15:17:51.320004+00, 2025-03-24 15:17:51.320004+00, f, null, null, null, null, null, null).
[SQL: INSERT INTO token (id, created_at, updated_at, is_metadata_parsed) VALUES ($1::UUID, $2::TIMESTAMP WITH TIME ZONE, $3::TIMESTAMP WITH TIME ZONE, $4::BOOLEAN) ON CONFLICT DO NOTHING]
[parameters: [('0195c8bb-4658-70c7-bc59-3a3dc1c44dd7', datetime.datetime(2025, 3, 24, 15, 17, 51, 320004), datetime.datetime(2025, 3, 24, 15, 17, 51, 320004), False), ('0195c8bb-4659-7f50-9866-e371d13f0f7e', datetime.datetime(2025, 3, 24, 15, 17, 51, 320113), datetime.datetime(2025, 3, 24, 15, 17, 51, 320113), False), ('0195c8bb-465a-7f4a-9374-ba0728088c22', datetime.datetime(2025, 3, 24, 15, 17, 51, 320124), datetime.datetime(2025, 3, 24, 15, 17, 51, 320124), False), ('0195c8bb-465b-7ec4-8367-79a4e1566cbf', datetime.datetime(2025, 3, 24, 15, 17, 51, 320131), datetime.datetime(2025, 3, 24, 15, 17, 51, 320131), False), ('0195c8bb-465c-7703-a6eb-80490c90efed', datetime.datetime(2025, 3, 24, 15, 17, 51, 320138), datetime.datetime(2025, 3, 24, 15, 17, 51, 320138), False), ('0195c8bb-465d-7410-8f52-ad688eac1962', datetime.datetime(2025, 3, 24, 15, 17, 51, 320143), datetime.datetime(2025, 3, 24, 15, 17, 51, 320143), False), ('0195c8bb-465e-7b2b-9cac-126244ab98ba', datetime.datetime(2025, 3, 24, 15, 17, 51, 320149), datetime.datetime(2025, 3, 24, 15, 17, 51, 320149), False), ('0195c8bb-465f-787a-aa7b-68e41807db16', datetime.datetime(2025, 3, 24, 15, 17, 51, 320156), datetime.datetime(2025, 3, 24, 15, 17, 51, 320156), False)  ... displaying 10 of 1000 total bound parameter sets ...  ('0195c8bb-4a3e-7c38-be29-d9251f101037', datetime.datetime(2025, 3, 24, 15, 17, 51, 326599), datetime.datetime(2025, 3, 24, 15, 17, 51, 326599), False), ('0195c8bb-4a3f-70f7-82b3-91e71d17a017', datetime.datetime(2025, 3, 24, 15, 17, 51, 326604), datetime.datetime(2025, 3, 24, 15, 17, 51, 326604), False)]]
(Background on this error at: https://sqlalche.me/e/20/gkpj) | Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 561, in _executemany
    return await self._connection.executemany(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 390, in executemany
    return await self._executemany(command, args, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 1988, in _executemany
    result, _ = await self._do_execute(
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 2024, in _do_execute
    result = await executor(stmt, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 268, in bind_execute_many
asyncpg.exceptions.NotNullViolationError: null value in column "address" of relation "token" violates not-null constraint
DETAIL:  Failing row contains (0195c8bb-4658-70c7-bc59-3a3dc1c44dd7, 2025-03-24 15:17:51.320004+00, 2025-03-24 15:17:51.320004+00, f, null, null, null, null, null, null).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1936, in _exec_single_context
    self.dialect.do_executemany(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 938, in do_executemany
    cursor.executemany(statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 573, in executemany
    return self._adapt_connection.await_(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 565, in _executemany
    self._handle_exception(error)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 497, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 780, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.IntegrityError: <class 'asyncpg.exceptions.NotNullViolationError'>: null value in column "address" of relation "token" violates not-null constraint
DETAIL:  Failing row contains (0195c8bb-4658-70c7-bc59-3a3dc1c44dd7, 2025-03-24 15:17:51.320004+00, 2025-03-24 15:17:51.320004+00, f, null, null, null, null, null, null).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/src/infra/celery/task_logger.py", line 12, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/celery/tasks.py", line 24, in collect_sol_prices_task
    asyncio.run(collect_prices_async())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/src/application/etl/sol_prices_collector.py", line 47, in collect_prices_async
    await load_prices_to_db(prices_to_load)
  File "/app/src/application/etl/sol_prices_collector.py", line 113, in load_prices_to_db
    await SQLAlchemyTokenRepository(session).bulk_create(
  File "/app/src/infra/db/sqlalchemy/repositories/generic_repository.py", line 97, in bulk_create
    await connection.execute(stmt, values)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py", line 657, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1936, in _exec_single_context
    self.dialect.do_executemany(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 938, in do_executemany
    cursor.executemany(statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 573, in executemany
    return self._adapt_connection.await_(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 565, in _executemany
    self._handle_exception(error)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 497, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 780, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.IntegrityError: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.NotNullViolationError'>: null value in column "address" of relation "token" violates not-null constraint
DETAIL:  Failing row contains (0195c8bb-4658-70c7-bc59-3a3dc1c44dd7, 2025-03-24 15:17:51.320004+00, 2025-03-24 15:17:51.320004+00, f, null, null, null, null, null, null).
[SQL: INSERT INTO token (id, created_at, updated_at, is_metadata_parsed) VALUES ($1::UUID, $2::TIMESTAMP WITH TIME ZONE, $3::TIMESTAMP WITH TIME ZONE, $4::BOOLEAN) ON CONFLICT DO NOTHING]
[parameters: [('0195c8bb-4658-70c7-bc59-3a3dc1c44dd7', datetime.datetime(2025, 3, 24, 15, 17, 51, 320004), datetime.datetime(2025, 3, 24, 15, 17, 51, 320004), False), ('0195c8bb-4659-7f50-9866-e371d13f0f7e', datetime.datetime(2025, 3, 24, 15, 17, 51, 320113), datetime.datetime(2025, 3, 24, 15, 17, 51, 320113), False), ('0195c8bb-465a-7f4a-9374-ba0728088c22', datetime.datetime(2025, 3, 24, 15, 17, 51, 320124), datetime.datetime(2025, 3, 24, 15, 17, 51, 320124), False), ('0195c8bb-465b-7ec4-8367-79a4e1566cbf', datetime.datetime(2025, 3, 24, 15, 17, 51, 320131), datetime.datetime(2025, 3, 24, 15, 17, 51, 320131), False), ('0195c8bb-465c-7703-a6eb-80490c90efed', datetime.datetime(2025, 3, 24, 15, 17, 51, 320138), datetime.datetime(2025, 3, 24, 15, 17, 51, 320138), False), ('0195c8bb-465d-7410-8f52-ad688eac1962', datetime.datetime(2025, 3, 24, 15, 17, 51, 320143), datetime.datetime(2025, 3, 24, 15, 17, 51, 320143), False), ('0195c8bb-465e-7b2b-9cac-126244ab98ba', datetime.datetime(2025, 3, 24, 15, 17, 51, 320149), datetime.datetime(2025, 3, 24, 15, 17, 51, 320149), False), ('0195c8bb-465f-787a-aa7b-68e41807db16', datetime.datetime(2025, 3, 24, 15, 17, 51, 320156), datetime.datetime(2025, 3, 24, 15, 17, 51, 320156), False)  ... displaying 10 of 1000 total bound parameter sets ...  ('0195c8bb-4a3e-7c38-be29-d9251f101037', datetime.datetime(2025, 3, 24, 15, 17, 51, 326599), datetime.datetime(2025, 3, 24, 15, 17, 51, 326599), False), ('0195c8bb-4a3f-70f7-82b3-91e71d17a017', datetime.datetime(2025, 3, 24, 15, 17, 51, 326604), datetime.datetime(2025, 3, 24, 15, 17, 51, 326604), False)]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

INFO 2025-03-24 15:20:19,525 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-24 15:20:19,592 sol_prices_collector Собираем цены с 2024-12-01 00:00:00+00:00 до 2025-03-24 15:20:19.592450+00:00...
DEBUG 2025-03-24 15:20:20,027 sol_prices_collector Собираем за период 2024-12-01 00:00:00+00:00 - 2025-03-24 15:20:19.592450+00:00
INFO 2025-03-24 15:20:20,187 sol_prices_collector Цены успешно собраны за период с {current_time} до {next_time}!
INFO 2025-03-24 15:20:20,194 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-24 15:22:15,884 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-24 15:22:15,950 sol_prices_collector Собираем цены с 2024-12-01 00:00:00+00:00 до 2025-03-24 15:22:15.950959+00:00...
DEBUG 2025-03-24 15:22:16,427 sol_prices_collector Собираем за период 2024-12-01 00:00:00+00:00 - 2025-03-24 15:22:15.950959+00:00
INFO 2025-03-24 15:22:16,583 sol_prices_collector Цены успешно собраны за период с 2024-12-01 00:00:00+00:00 до 2025-03-24 15:22:15.950959+00:00!
INFO 2025-03-24 15:22:16,590 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-24 15:23:16,585 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
ERROR 2025-03-24 15:23:16,607 task_logger Ошибка при выполнении задачи collect_sol_prices_task: Task <Task pending name='Task-7' coro=<collect_prices_async() running at /app/src/application/etl/sol_prices_collector.py:21> cb=[_run_until_complete_cb() at /usr/local/lib/python3.11/asyncio/base_events.py:181]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop | Traceback (most recent call last):
  File "/app/src/infra/celery/task_logger.py", line 12, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/celery/tasks.py", line 24, in collect_sol_prices_task
    asyncio.run(collect_prices_async())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/src/application/etl/sol_prices_collector.py", line 21, in collect_prices_async
    token = await get_sol_token()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/application/etl/sol_prices_collector.py", line 99, in get_sol_token
    return await SQLAlchemyTokenRepository(session).get_by_address(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/db/sqlalchemy/repositories/token.py", line 27, in get_by_address
    result = await self._session.scalars(stmt)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 574, in scalars
    result = await self.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 461, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2358, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 568, in execute
    self._adapt_connection.await_(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 504, in _prepare_and_execute
    await adapt_connection._start_transaction()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 833, in _start_transaction
    self._handle_exception(error)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 782, in _handle_exception
    raise error
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 831, in _start_transaction
    await self._transaction.start()
  File "/usr/local/lib/python3.11/site-packages/asyncpg/transaction.py", line 146, in start
    await self._connection.execute(query)
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 349, in execute
    result = await self._protocol.query(query, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 375, in query
RuntimeError: Task <Task pending name='Task-7' coro=<collect_prices_async() running at /app/src/application/etl/sol_prices_collector.py:21> cb=[_run_until_complete_cb() at /usr/local/lib/python3.11/asyncio/base_events.py:181]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop

INFO 2025-03-24 15:23:58,823 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
ERROR 2025-03-24 15:23:58,890 sol_prices_collector None
ERROR 2025-03-24 15:23:58,890 sol_prices_collector None
ERROR 2025-03-24 15:23:58,901 task_logger Ошибка при выполнении задачи collect_sol_prices_task: 'NoneType' object has no attribute 'minute' | Traceback (most recent call last):
  File "/app/src/infra/celery/task_logger.py", line 12, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/celery/tasks.py", line 24, in collect_sol_prices_task
    asyncio.run(collect_prices_async())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/src/application/etl/sol_prices_collector.py", line 22, in collect_prices_async
    start_time, end_time = await get_start_end_time(token)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/application/etl/sol_prices_collector.py", line 56, in get_start_end_time
    logger.error(latest_token_price.minute)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'minute'

INFO 2025-03-24 15:25:43,269 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-24 15:25:43,334 sol_prices_collector Собираем цены с 2024-12-01 00:00:00+00:00 до 2025-03-24 15:25:43.334507+00:00...
DEBUG 2025-03-24 15:25:43,741 sol_prices_collector Собираем за период 2024-12-01 00:00:00+00:00 - 2025-03-24 15:25:43.334507+00:00
INFO 2025-03-24 15:25:43,876 sol_prices_collector Цены успешно собраны за период с 2024-12-01 00:00:00+00:00 до 2025-03-24 15:25:43.334507+00:00!
INFO 2025-03-24 15:25:43,881 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-24 15:26:30,533 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-24 15:26:30,597 sol_prices_collector Собираем цены с 2025-03-15 20:42:00+00:00 до 2025-03-24 15:26:30.597949+00:00...
DEBUG 2025-03-24 15:26:31,494 sol_prices_collector Собираем за период 2025-03-15 20:42:00+00:00 - 2025-03-24 15:26:30.597949+00:00
INFO 2025-03-24 15:26:31,695 sol_prices_collector Цены успешно собраны за период с 2025-03-15 20:42:00+00:00 до 2025-03-24 15:26:30.597949+00:00!
INFO 2025-03-24 15:26:31,706 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-24 15:28:18,184 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-24 15:28:18,250 sol_prices_collector Собираем цены с 2025-03-16 13:21:00+00:00 до 2025-03-24 15:28:18.250268+00:00...
DEBUG 2025-03-24 15:28:18,696 sol_prices_collector Собираем за период 2025-03-16 13:21:00+00:00 - 2025-03-24 15:28:18.250268+00:00
INFO 2025-03-24 15:28:18,852 sol_prices_collector Цены успешно собраны за период с 2025-03-16 13:21:00+00:00 до 2025-03-24 15:28:18.250268+00:00!
INFO 2025-03-24 15:28:18,858 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-24 15:29:18,853 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
ERROR 2025-03-24 15:29:18,878 task_logger Ошибка при выполнении задачи collect_sol_prices_task: Task <Task pending name='Task-7' coro=<collect_prices_async() running at /app/src/application/etl/sol_prices_collector.py:21> cb=[_run_until_complete_cb() at /usr/local/lib/python3.11/asyncio/base_events.py:181]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop | Traceback (most recent call last):
  File "/app/src/infra/celery/task_logger.py", line 12, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/celery/tasks.py", line 24, in collect_sol_prices_task
    asyncio.run(collect_prices_async())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/src/application/etl/sol_prices_collector.py", line 21, in collect_prices_async
    token = await get_sol_token()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/application/etl/sol_prices_collector.py", line 101, in get_sol_token
    return await SQLAlchemyTokenRepository(session).get_by_address(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/db/sqlalchemy/repositories/token.py", line 27, in get_by_address
    result = await self._session.scalars(stmt)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 574, in scalars
    result = await self.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 461, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2358, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 568, in execute
    self._adapt_connection.await_(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 504, in _prepare_and_execute
    await adapt_connection._start_transaction()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 833, in _start_transaction
    self._handle_exception(error)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 782, in _handle_exception
    raise error
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 831, in _start_transaction
    await self._transaction.start()
  File "/usr/local/lib/python3.11/site-packages/asyncpg/transaction.py", line 146, in start
    await self._connection.execute(query)
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 349, in execute
    result = await self._protocol.query(query, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 375, in query
RuntimeError: Task <Task pending name='Task-7' coro=<collect_prices_async() running at /app/src/application/etl/sol_prices_collector.py:21> cb=[_run_until_complete_cb() at /usr/local/lib/python3.11/asyncio/base_events.py:181]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop

INFO 2025-03-24 15:29:37,761 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-24 15:29:37,837 sol_prices_collector Собираем цены с 2025-03-17 06:00:00+00:00 до 2025-03-24 15:29:37.837797+00:00...
DEBUG 2025-03-24 15:29:38,722 sol_prices_collector Собираем за период 2025-03-17 06:00:00+00:00 - 2025-03-24 15:29:37.837797+00:00
ERROR 2025-03-24 15:29:38,827 sol_prices_collector 1000
ERROR 2025-03-24 15:29:38,827 sol_prices_collector 1000
ERROR 2025-03-24 15:29:38,827 sol_prices_collector 1000
ERROR 2025-03-24 15:29:38,827 sol_prices_collector 1000
INFO 2025-03-24 15:29:38,877 sol_prices_collector Цены успешно собраны за период с 2025-03-17 06:00:00+00:00 до 2025-03-24 15:29:37.837797+00:00!
INFO 2025-03-24 15:29:38,882 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-24 15:30:38,878 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
ERROR 2025-03-24 15:30:38,903 task_logger Ошибка при выполнении задачи collect_sol_prices_task: Task <Task pending name='Task-7' coro=<collect_prices_async() running at /app/src/application/etl/sol_prices_collector.py:21> cb=[_run_until_complete_cb() at /usr/local/lib/python3.11/asyncio/base_events.py:181]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop | Traceback (most recent call last):
  File "/app/src/infra/celery/task_logger.py", line 12, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/celery/tasks.py", line 24, in collect_sol_prices_task
    asyncio.run(collect_prices_async())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/src/application/etl/sol_prices_collector.py", line 21, in collect_prices_async
    token = await get_sol_token()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/application/etl/sol_prices_collector.py", line 101, in get_sol_token
    return await SQLAlchemyTokenRepository(session).get_by_address(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/db/sqlalchemy/repositories/token.py", line 27, in get_by_address
    result = await self._session.scalars(stmt)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 574, in scalars
    result = await self.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 461, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2358, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 568, in execute
    self._adapt_connection.await_(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 504, in _prepare_and_execute
    await adapt_connection._start_transaction()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 833, in _start_transaction
    self._handle_exception(error)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 782, in _handle_exception
    raise error
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 831, in _start_transaction
    await self._transaction.start()
  File "/usr/local/lib/python3.11/site-packages/asyncpg/transaction.py", line 146, in start
    await self._connection.execute(query)
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 349, in execute
    result = await self._protocol.query(query, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 375, in query
RuntimeError: Task <Task pending name='Task-7' coro=<collect_prices_async() running at /app/src/application/etl/sol_prices_collector.py:21> cb=[_run_until_complete_cb() at /usr/local/lib/python3.11/asyncio/base_events.py:181]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop

INFO 2025-03-24 15:30:51,255 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-24 15:30:51,319 sol_prices_collector Собираем цены с 2025-03-17 22:39:00+00:00 до 2025-03-18 15:19:00+00:00...
DEBUG 2025-03-24 15:30:51,722 sol_prices_collector Собираем за период 2025-03-17 22:39:00+00:00 - 2025-03-18 15:19:00+00:00
INFO 2025-03-24 15:30:51,823 sol_prices_collector Собираем цены с 2025-03-18 15:19:00+00:00 до 2025-03-19 07:59:00+00:00...
DEBUG 2025-03-24 15:30:52,167 sol_prices_collector Собираем за период 2025-03-18 15:19:00+00:00 - 2025-03-19 07:59:00+00:00
INFO 2025-03-24 15:30:52,268 sol_prices_collector Собираем цены с 2025-03-19 07:59:00+00:00 до 2025-03-20 00:39:00+00:00...
DEBUG 2025-03-24 15:30:52,618 sol_prices_collector Собираем за период 2025-03-19 07:59:00+00:00 - 2025-03-20 00:39:00+00:00
INFO 2025-03-24 15:30:52,719 sol_prices_collector Собираем цены с 2025-03-20 00:39:00+00:00 до 2025-03-20 17:19:00+00:00...
DEBUG 2025-03-24 15:30:53,070 sol_prices_collector Собираем за период 2025-03-20 00:39:00+00:00 - 2025-03-20 17:19:00+00:00
INFO 2025-03-24 15:30:53,170 sol_prices_collector Собираем цены с 2025-03-20 17:19:00+00:00 до 2025-03-21 09:59:00+00:00...
DEBUG 2025-03-24 15:30:53,517 sol_prices_collector Собираем за период 2025-03-20 17:19:00+00:00 - 2025-03-21 09:59:00+00:00
INFO 2025-03-24 15:30:53,618 sol_prices_collector Собираем цены с 2025-03-21 09:59:00+00:00 до 2025-03-22 02:39:00+00:00...
DEBUG 2025-03-24 15:30:54,026 sol_prices_collector Собираем за период 2025-03-21 09:59:00+00:00 - 2025-03-22 02:39:00+00:00
INFO 2025-03-24 15:30:54,126 sol_prices_collector Собираем цены с 2025-03-22 02:39:00+00:00 до 2025-03-22 19:19:00+00:00...
DEBUG 2025-03-24 15:30:54,471 sol_prices_collector Собираем за период 2025-03-22 02:39:00+00:00 - 2025-03-22 19:19:00+00:00
INFO 2025-03-24 15:30:54,572 sol_prices_collector Собираем цены с 2025-03-22 19:19:00+00:00 до 2025-03-23 11:59:00+00:00...
DEBUG 2025-03-24 15:30:54,918 sol_prices_collector Собираем за период 2025-03-22 19:19:00+00:00 - 2025-03-23 11:59:00+00:00
INFO 2025-03-24 15:30:55,019 sol_prices_collector Собираем цены с 2025-03-23 11:59:00+00:00 до 2025-03-24 04:39:00+00:00...
DEBUG 2025-03-24 15:30:55,367 sol_prices_collector Собираем за период 2025-03-23 11:59:00+00:00 - 2025-03-24 04:39:00+00:00
INFO 2025-03-24 15:30:55,467 sol_prices_collector Собираем цены с 2025-03-24 04:39:00+00:00 до 2025-03-24 15:30:51.319842+00:00...
DEBUG 2025-03-24 15:30:55,796 sol_prices_collector Собираем за период 2025-03-24 04:39:00+00:00 - 2025-03-24 15:30:51.319842+00:00
ERROR 2025-03-24 15:30:55,937 sol_prices_collector 9652
ERROR 2025-03-24 15:30:55,938 sol_prices_collector 9652
ERROR 2025-03-24 15:30:55,938 sol_prices_collector 9652
ERROR 2025-03-24 15:30:55,938 sol_prices_collector 9652
INFO 2025-03-24 15:30:56,312 sol_prices_collector Цены успешно собраны за период с 2025-03-17 22:39:00+00:00 до 2025-03-24 15:30:51.319842+00:00!
INFO 2025-03-24 15:30:56,320 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-24 23:57:27,202 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-24 23:57:27,203 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-24 23:57:27,203 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-24 23:57:27,205 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-24 23:57:27,290 sol_prices_collector Собираем цены с 2025-03-24 15:30:00+00:00 до 2025-03-24 23:57:27.289973+00:00...
INFO 2025-03-24 23:57:27,290 sol_prices_collector Собираем цены с 2025-03-24 15:30:00+00:00 до 2025-03-24 23:57:27.290334+00:00...
INFO 2025-03-24 23:57:27,294 sol_prices_collector Собираем цены с 2025-03-24 15:30:00+00:00 до 2025-03-24 23:57:27.294323+00:00...
INFO 2025-03-24 23:57:27,308 sol_prices_collector Собираем цены с 2025-03-24 15:30:00+00:00 до 2025-03-24 23:57:27.308714+00:00...
DEBUG 2025-03-24 23:57:28,621 sol_prices_collector Собираем за период 2025-03-24 15:30:00+00:00 - 2025-03-24 23:57:27.290334+00:00
DEBUG 2025-03-24 23:57:28,622 sol_prices_collector Собираем за период 2025-03-24 15:30:00+00:00 - 2025-03-24 23:57:27.294323+00:00
DEBUG 2025-03-24 23:57:28,623 sol_prices_collector Собираем за период 2025-03-24 15:30:00+00:00 - 2025-03-24 23:57:27.289973+00:00
DEBUG 2025-03-24 23:57:28,625 sol_prices_collector Собираем за период 2025-03-24 15:30:00+00:00 - 2025-03-24 23:57:27.308714+00:00
ERROR 2025-03-24 23:57:28,724 sol_prices_collector 508
ERROR 2025-03-24 23:57:28,724 sol_prices_collector 508
ERROR 2025-03-24 23:57:28,724 sol_prices_collector 508
ERROR 2025-03-24 23:57:28,725 sol_prices_collector 508
ERROR 2025-03-24 23:57:28,725 sol_prices_collector 508
ERROR 2025-03-24 23:57:28,726 sol_prices_collector 508
ERROR 2025-03-24 23:57:28,726 sol_prices_collector 508
ERROR 2025-03-24 23:57:28,726 sol_prices_collector 508
ERROR 2025-03-24 23:57:28,727 sol_prices_collector 508
ERROR 2025-03-24 23:57:28,727 sol_prices_collector 508
ERROR 2025-03-24 23:57:28,727 sol_prices_collector 508
ERROR 2025-03-24 23:57:28,728 sol_prices_collector 508
ERROR 2025-03-24 23:57:28,728 sol_prices_collector 508
ERROR 2025-03-24 23:57:28,729 sol_prices_collector 508
ERROR 2025-03-24 23:57:28,729 sol_prices_collector 508
ERROR 2025-03-24 23:57:28,729 sol_prices_collector 508
INFO 2025-03-24 23:57:28,760 sol_prices_collector Цены успешно собраны за период с 2025-03-24 15:30:00+00:00 до 2025-03-24 23:57:27.290334+00:00!
INFO 2025-03-24 23:57:28,766 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-24 23:57:28,772 sol_prices_collector Цены успешно собраны за период с 2025-03-24 15:30:00+00:00 до 2025-03-24 23:57:27.289973+00:00!
INFO 2025-03-24 23:57:28,772 sol_prices_collector Цены успешно собраны за период с 2025-03-24 15:30:00+00:00 до 2025-03-24 23:57:27.308714+00:00!
INFO 2025-03-24 23:57:28,775 sol_prices_collector Цены успешно собраны за период с 2025-03-24 15:30:00+00:00 до 2025-03-24 23:57:27.294323+00:00!
INFO 2025-03-24 23:57:28,777 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-24 23:57:28,777 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-24 23:57:28,780 task_logger Задача collect_sol_prices_task успешно завершена!
INFO 2025-03-24 23:58:28,760 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-24 23:58:28,771 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-24 23:58:28,772 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
INFO 2025-03-24 23:58:28,775 task_logger Запуск задачи collect_sol_prices_task с параметрами: args=(), kwargs={}
ERROR 2025-03-24 23:58:28,808 task_logger Ошибка при выполнении задачи collect_sol_prices_task: Task <Task pending name='Task-7' coro=<collect_prices_async() running at /app/src/application/etl/sol_prices_collector.py:21> cb=[_run_until_complete_cb() at /usr/local/lib/python3.11/asyncio/base_events.py:181]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop | Traceback (most recent call last):
  File "/app/src/infra/celery/task_logger.py", line 12, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/celery/tasks.py", line 24, in collect_sol_prices_task
    asyncio.run(collect_prices_async())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/src/application/etl/sol_prices_collector.py", line 21, in collect_prices_async
    token = await get_sol_token()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/application/etl/sol_prices_collector.py", line 101, in get_sol_token
    return await SQLAlchemyTokenRepository(session).get_by_address(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/db/sqlalchemy/repositories/token.py", line 27, in get_by_address
    result = await self._session.scalars(stmt)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 574, in scalars
    result = await self.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 461, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2358, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 568, in execute
    self._adapt_connection.await_(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 504, in _prepare_and_execute
    await adapt_connection._start_transaction()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 833, in _start_transaction
    self._handle_exception(error)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 782, in _handle_exception
    raise error
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 831, in _start_transaction
    await self._transaction.start()
  File "/usr/local/lib/python3.11/site-packages/asyncpg/transaction.py", line 146, in start
    await self._connection.execute(query)
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 349, in execute
    result = await self._protocol.query(query, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 375, in query
RuntimeError: Task <Task pending name='Task-7' coro=<collect_prices_async() running at /app/src/application/etl/sol_prices_collector.py:21> cb=[_run_until_complete_cb() at /usr/local/lib/python3.11/asyncio/base_events.py:181]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop

ERROR 2025-03-24 23:58:28,808 task_logger Ошибка при выполнении задачи collect_sol_prices_task: Task <Task pending name='Task-7' coro=<collect_prices_async() running at /app/src/application/etl/sol_prices_collector.py:21> cb=[_run_until_complete_cb() at /usr/local/lib/python3.11/asyncio/base_events.py:181]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop | Traceback (most recent call last):
  File "/app/src/infra/celery/task_logger.py", line 12, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/celery/tasks.py", line 24, in collect_sol_prices_task
    asyncio.run(collect_prices_async())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/src/application/etl/sol_prices_collector.py", line 21, in collect_prices_async
    token = await get_sol_token()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/application/etl/sol_prices_collector.py", line 101, in get_sol_token
    return await SQLAlchemyTokenRepository(session).get_by_address(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/db/sqlalchemy/repositories/token.py", line 27, in get_by_address
    result = await self._session.scalars(stmt)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 574, in scalars
    result = await self.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 461, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2358, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 568, in execute
    self._adapt_connection.await_(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 504, in _prepare_and_execute
    await adapt_connection._start_transaction()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 833, in _start_transaction
    self._handle_exception(error)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 782, in _handle_exception
    raise error
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 831, in _start_transaction
    await self._transaction.start()
  File "/usr/local/lib/python3.11/site-packages/asyncpg/transaction.py", line 146, in start
    await self._connection.execute(query)
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 349, in execute
    result = await self._protocol.query(query, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 375, in query
RuntimeError: Task <Task pending name='Task-7' coro=<collect_prices_async() running at /app/src/application/etl/sol_prices_collector.py:21> cb=[_run_until_complete_cb() at /usr/local/lib/python3.11/asyncio/base_events.py:181]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop

ERROR 2025-03-24 23:58:28,808 task_logger Ошибка при выполнении задачи collect_sol_prices_task: Task <Task pending name='Task-7' coro=<collect_prices_async() running at /app/src/application/etl/sol_prices_collector.py:21> cb=[_run_until_complete_cb() at /usr/local/lib/python3.11/asyncio/base_events.py:181]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop | Traceback (most recent call last):
  File "/app/src/infra/celery/task_logger.py", line 12, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/celery/tasks.py", line 24, in collect_sol_prices_task
    asyncio.run(collect_prices_async())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/src/application/etl/sol_prices_collector.py", line 21, in collect_prices_async
    token = await get_sol_token()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/application/etl/sol_prices_collector.py", line 101, in get_sol_token
    return await SQLAlchemyTokenRepository(session).get_by_address(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/db/sqlalchemy/repositories/token.py", line 27, in get_by_address
    result = await self._session.scalars(stmt)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 574, in scalars
    result = await self.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 461, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2358, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 568, in execute
    self._adapt_connection.await_(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 504, in _prepare_and_execute
    await adapt_connection._start_transaction()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 833, in _start_transaction
    self._handle_exception(error)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 782, in _handle_exception
    raise error
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 831, in _start_transaction
    await self._transaction.start()
  File "/usr/local/lib/python3.11/site-packages/asyncpg/transaction.py", line 146, in start
    await self._connection.execute(query)
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 349, in execute
    result = await self._protocol.query(query, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 375, in query
RuntimeError: Task <Task pending name='Task-7' coro=<collect_prices_async() running at /app/src/application/etl/sol_prices_collector.py:21> cb=[_run_until_complete_cb() at /usr/local/lib/python3.11/asyncio/base_events.py:181]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop

ERROR 2025-03-24 23:58:28,808 task_logger Ошибка при выполнении задачи collect_sol_prices_task: Task <Task pending name='Task-7' coro=<collect_prices_async() running at /app/src/application/etl/sol_prices_collector.py:21> cb=[_run_until_complete_cb() at /usr/local/lib/python3.11/asyncio/base_events.py:181]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop | Traceback (most recent call last):
  File "/app/src/infra/celery/task_logger.py", line 12, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/celery/tasks.py", line 24, in collect_sol_prices_task
    asyncio.run(collect_prices_async())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/src/application/etl/sol_prices_collector.py", line 21, in collect_prices_async
    token = await get_sol_token()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/application/etl/sol_prices_collector.py", line 101, in get_sol_token
    return await SQLAlchemyTokenRepository(session).get_by_address(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/infra/db/sqlalchemy/repositories/token.py", line 27, in get_by_address
    result = await self._session.scalars(stmt)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 574, in scalars
    result = await self.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 461, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2358, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 568, in execute
    self._adapt_connection.await_(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 504, in _prepare_and_execute
    await adapt_connection._start_transaction()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 833, in _start_transaction
    self._handle_exception(error)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 782, in _handle_exception
    raise error
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 831, in _start_transaction
    await self._transaction.start()
  File "/usr/local/lib/python3.11/site-packages/asyncpg/transaction.py", line 146, in start
    await self._connection.execute(query)
  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 349, in execute
    result = await self._protocol.query(query, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 375, in query
RuntimeError: Task <Task pending name='Task-7' coro=<collect_prices_async() running at /app/src/application/etl/sol_prices_collector.py:21> cb=[_run_until_complete_cb() at /usr/local/lib/python3.11/asyncio/base_events.py:181]> got Future <Future pending cb=[BaseProtocol._on_waiter_completed()]> attached to a different loop

